feat(#15) add github actions

diff --git a/app/.github/workflows/check.yml b/app/.github/workflows/check.yml
--- a/app/.github/workflows/check.yml
+++ b/app/.github/workflows/check.yml
@@ -5,6 +5,8 @@ on:
     secrets:
       EXPO_TOKEN:
         required: true
+      GOOGLE_PLAY_SERVICE_ACCOUNT_JSON:
+        required: true
     inputs:
       DOMAIN:
         required: true
@@ -12,9 +14,11 @@ on:
 
 jobs:
   check-config:
-    runs-on: ubuntu-latest
+    #runs-on: ubuntu-latest
+    runs-on: main-n
     steps:
       - name: Check required config
         run: |
           [[ -z "${{ secrets.EXPO_TOKEN }}" ]] && echo "❌ Missing secrets.EXPO_TOKEN" && exit 1
+          [[ -z "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}" ]] && echo "❌ Missing secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON" && exit 1
           echo "✅ All required secrets and vars are set"
